### ISSUE TITLE
1. Occurence - Hash

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#1]
Count the occurrences of various alphabet letters in an input string and store it in hash.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/1Hashes

**Comment by segunadeleye** [comment]
You are to use monkey patching. This simply means you can open a built-in ruby class and add methods to it or even over-write the built-in methods of the class.

For example, let's add a #do_something method to the String class

```
class String
  def do_something
    self.string_method
  end
end
```

This method is now available to the string objects. Hence I can call the method on a string like this

`'I am just a string'.do_somthing'`

Within the method, the string object can be referenced with `self`. In other words `self` refers to `'I am just a string'`

This is the concept of monkey patching. This concept will be used for most of your exercises.

Also remove the `_` at the beginning of your variable names.

Use two-space indentation Indent blocks within a method definition.

Ask questions anywhere you have doubts.

**Comment by ghost** [comment]
I used the monkey patching in most of the exercises that requires it's usage. I will remove all underscores at the beginning of variable name (it's makes it easier to differentiate between local and other variable types), I will also use the two-space indentation system. Thanks.

**Comment by segunadeleye** [comment]
https://github.com/adebayo-dealdey/RubyTrack/blob/master/1Hashes/lib/string.rb#L6 could be written as
`refined_word     = ignorecase ? downcase : self`
Here `self` is used implicitly. So within the method, `downcase` is same as `self.downcase`

https://github.com/adebayo-dealdey/RubyTrack/blob/master/1Hashes/lib/string.rb#L9 and https://github.com/adebayo-dealdey/RubyTrack/blob/master/1Hashes/lib/string.rb#L10 can be one line. You don't have to save the value into `nos` if you are not using it anywhere else.

You are to get the count of only alphabet letters. Aa-Zz. You are counting all characters, including space.

**Comment by ghost** [comment]
I just made the adjustment now, kindly check it out for review. Thanks.

**Comment by segunadeleye** [comment]
Looks good.
