### ISSUE TITLE
10. Hash - Inject

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#10]
Write a method that groups the above hash into 2 groups of 'even' and 'odd' length using 'inject'.Eg: ['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'] -> {odd: [["x", 5], ["abc", "def", 234]], even: [[1234, "abcd", "mnop", "zZzZ"]]}

https://github.com/adebayo-dealdey/RubyTrack/tree/master/EvenOdd

**Comment by segunadeleye** [comment]
- See `odd?` and `even?` methods.
- File name should match class name.
- For `sort_inject` you can pass `sorted_hash` as the argument to inject which will be the initial value of `map`

**Comment by ghost** [comment]
I just did all the adjustments, passing argument to inject I didn't do, I will if you insist though.

**Comment by segunadeleye** [comment]
Please add the link to the file in which `sort_hash_to_even_odd` is defined.
In `sort_hash_to_even_odd`, why are you extracting the hash keys, what about calling `each` on the hash it self. Also, did you check out `odd?` and `even?` ?

**Comment by ghost** [comment]
1. I required the file in which `sort_hash_to_even_odd` is defined in the `lib/hash.rb` file which is all ready included in the `main.rb` file
2. Done.

**Comment by ghost** [comment]
https://github.com/adebayo-dealdey/RubyTrack/blob/master/Hash/lib/array.rb

That is the file with the `sort_hash_to_even_odd` function. Thanks.

**Comment by segunadeleye** [comment]
Looks good.
