### ISSUE TITLE
12. Character Count - Ranges

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#12]
Write a method that returns the no of various lowercase, uppercase, digits and special characters used in the string. Make use of Ranges.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Ranges

**Comment by segunadeleye** [comment]
You are to make use of ranges. Not regex

**Comment by ghost** [comment]
Done as you have said.

**Comment by segunadeleye** [comment]
- Use range literal.
- What about saving the character count in a hash.
- `sentence = self`...is this needed?

**Comment by ghost** [comment]
Done

**Comment by segunadeleye** [comment]
You didn't make any changes with respect to my last feedback

**Comment by ghost** [comment]
I havent pushed.. I will right away.

**Comment by segunadeleye** [comment]
https://github.com/adebayo-dealdey/RubyTrack/blob/master/Ranges/lib/string.rb#L7
Looks good. However, you need to correct this

**Comment by ghost** [comment]
Done. Thanks.
