### ISSUE TITLE
13. Factorial - Ranges

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#13]
Rewrite factorial method using ranges.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Factorial

**Comment by segunadeleye** [comment]
There's another method that can be used in place of `each`

**Comment by ghost** [comment]
I can't think of any other one, kindly suggest if required please.

**Comment by segunadeleye** [comment]
How about `inject`?

**Comment by ghost** [comment]
Thanks. Done

**Comment by segunadeleye** [comment]
Looks good
