### ISSUE TITLE
14. Reverse Sentence

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#14]
Use string methods to reverse the words arrangement in a sentence.Eg: "An apple a day keeps the doctor away" -> "away doctor the keeps day a apple An"

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Reverse

**Comment by segunadeleye** [comment]
https://github.com/adebayo-dealdey/RubyTrack/blob/master/Reverse/lib/string.rb#L12 and https://github.com/adebayo-dealdey/RubyTrack/blob/master/Reverse/lib/string.rb#L13 can be just a line.

**Comment by ghost** [comment]
I just did adjusted that. Thanks.

**Comment by segunadeleye** [comment]
Looks good
