### ISSUE TITLE
15. Prime Numbers

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#15]
Step Define a method to find all prime numbers upto n using 'step' function.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Prime

**Comment by segunadeleye** [comment]
Can we call the method on the user_input instead of passing it as an argument.
Look at calling step on a Range object.
Also look at the Prime class.

**Comment by ghost** [comment]
Done thanks.

**Comment by segunadeleye** [comment]
Looks good.
- However, note that the default argument for `Range#step` is 1. So in this case, there is no need to pass 1 as an argument to `step`

**Comment by ghost** [comment]
Done
