### ISSUE TITLE
16. Highlight Search Result

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#16]
Write a search method that searches for a letter or word in a user input string and highlights the searched element. Also it should display the total no of searches found.
Eg: If user enters string to be searched as "Can you can a can as a canner can can a can?" and word to be searched is 'can' then output should be:(Can) you (can) a (can) as a (can)ner (can) (can) a (can)?Total Occurences found: 7

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Highlight

**Comment by segunadeleye** [comment]
- `String()` is not needed. Input is already a string object.
- Use `do end` for multi-line blocks.
- Always use string interpolation in place of string concatenation
- Check out `gsub!`
- Move printing search result to main.rb.

**Comment by ghost** [comment]
I just made the necessary adjustments, kindly check it out if it meets your requirements. Thanks.

**Comment by segunadeleye** [comment]
Looks good
Remove commented code
https://github.com/adebayo-dealdey/RubyTrack/blob/master/Highlight/bin/main.rb#L10 : Use string interpolation

**Comment by ghost** [comment]
Done... Thanks.
