### ISSUE TITLE
17. Sum Time

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#17]
Write a method that sums up 2 24-hour time values(h:m:s). Validate the time using regular expressions.Eg: ("0:45:34","0:15:58") -> 01:01:32 ; ("11:23:07","22:53:45") -> 1 day & 10:16:52

https://github.com/adebayo-dealdey/RubyTrack/tree/master/SumTime

**Comment by segunadeleye** [comment]
- Correct the definition of class methods.
- Why have you used this `summed_time = String('')`. And why did you create a `String` class?
- Save the regex in a constant.

**Comment by ghost** [comment]
I created `String` class for experimental purpose, It can convert to time seconds without it been from a time class object. I was experimenting with the classes.
I don't understand what you meant by correcting of class methods.
Others are fixed. Thanks.

**Comment by segunadeleye** [comment]
1. I don't understand what you meant by correcting of class methods.
2. using `self` instead of the class name.

All fine now
