### ISSUE TITLE
19. Interest Difference

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#19]
Create a class Interest that gives the user the difference in amount calculated simply and compoundedly. Initialise class with a block. 'p' and 't' are entered by user. Take 'r' = 10% pa.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Interest

**Comment by segunadeleye** [comment]
- Since `rate` is a constant, there is no need assigning it within the block. What about setting within
- Try running the code without adding `&block` to the parameters list.
- Is there a reason for using these? How about @principal

```
self.principal
self.time
self.rate
```
- Why have you chosen to make the methods protected?

**Comment by segunadeleye** [comment]
Additional Points:
- Did you know `10 / 100.00` can be `0.1`
- You are converting to float multiple times after doing the conversion before assigning or passing them to the methods. Is this needed?
- Why use `begin-end-unless` and not `unless`.

**Comment by ghost** [comment]
> Why have you chosen to make the methods protected?
> Ans: I don't want to functions accessible outside besides any class inheriting it.
> 
> Did you know `10 / 100.00` can be `0.1`
> Ans: Used that for readability, to know how I got to arrive at 0.1

Rest: Done. Kindly Review

**Comment by segunadeleye** [comment]
Okay cool...
Everything looks fine now
