### ISSUE TITLE
2. Replace - Regex

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#2]
Ask user to enter text. Replace each vowel in the text with a '*' using regular expression.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Regex

**Comment by segunadeleye** [comment]
Use monkey patching

`/a|e|i|o|u|A|E|I|O|U/` can be written in a more concise way. Look at putting patterns in `[]`

Readability is a very important concept in programming.
`word.empty? || word =~ /^\s*$/ ? 'You did not supply anything' : word.gsub(/a|e|i|o|u|A|E|I|O|U/, '*'`
This can be written in a more readable format.

**Comment by ghost** [comment]
Done the fix

**Comment by segunadeleye** [comment]
You don't have to use `self` explicitly. You can simply use `empty?` and `gsub` without calling them on `self`. I'll close now, but make the changes.

**Comment by ghost** [comment]
I just did , thanks
