### ISSUE TITLE
20. Factorial - Exception Catcher

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#20]
Add exception handling for negative numbers in factorial program.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/NegativeFactorial

**Comment by segunadeleye** [comment]
Why raise another exception after rescuing one exception.
Raise the exception within the class and handle it once either within the class or main.rb.

**Comment by ghost** [comment]
Done! Thanks.

**Comment by segunadeleye** [comment]
Do you need the block of code to be in `begin end`?

**Comment by ghost** [comment]
I guess it is needed since there will be a rescue line there, suggest please.

**Comment by segunadeleye** [comment]
Try it without `begin`

**Comment by ghost** [comment]
Would I Still be able to use `Exception => e` as needed?

**Comment by ghost** [comment]
Done

**Comment by segunadeleye** [comment]
Good
