### ISSUE TITLE
21. Name - Raise

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#21]
Create a class 'Name' with two attributes firstname and lastname. Neither of them can be blank and the first letter of firstname must be capital. Implement using 'raise'.Try using custom Exceptions.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Name

**Comment by segunadeleye** [comment]
- You are to validate before assigning the names to the instance variables.
- We do not need to create an instance of the exception classes. `raise` method takes a second argument.
- `attr_reader :first_name, :last_name` is not needed if they are not using them.

**Comment by ghost** [comment]
Done

**Comment by segunadeleye** [comment]
- There is no instance variables. You are supposed to validate, and if validation passes, you assign the values to the instance variables.
- How about moving the validation logic to a different method?
- Do we still need the `initialize` methods in the exception classes.

**Comment by ghost** [comment]
You told me to validate before assigning names to variables and remove variables if there isn't any need for them.

**Comment by ghost** [comment]
Done

**Comment by segunadeleye** [comment]
Almost there. Let's discuss this once

**Comment by ghost** [comment]
How do we do that?

**Comment by ghost** [comment]
Done, I'll Push

**Comment by segunadeleye** [comment]
Did you know that you do not need to return `true` for `validate?` method?

**Comment by segunadeleye** [comment]
Looks good
