### ISSUE TITLE
4. Palindrome

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#4]
Output whether the input string is palindrome. The program quits when user enters 'q/Q'.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Palindrome

**Comment by segunadeleye** [comment]
Use monkey patching.

An `if-else` statement will be a better option than `case-when-else` for short list of conditions. We only have two possible outcomes here.

One-letter and two-letter words are also a valid.

**Comment by ghost** [comment]
Thanks. Done the fix, kindly review.

**Comment by segunadeleye** [comment]
There is a String method that reverses a string.

Why are you using attr_reader and instance methods? `word` and `reverse_word` are not used outside the class nor are they used outside the method.

**Comment by ghost** [comment]
I just reformat the code, thanks for the correction.

**Comment by segunadeleye** [comment]
Why use `scan()`? Is it needed?

**Comment by ghost** [comment]
No it isn't needed. Thanks,

**Comment by segunadeleye** [comment]
Looks good.

```
word         = downcase
reverse_word = reverse.downcase
if word == reverse_word
```

Note that these 3 lines above can be just one line.
`if downcase == reverse.downcase`
Since the variables are not reused, there is no need to declare them.
The only exception is if using variables enhances readability.

**Comment by ghost** [comment]
Readability it is.
