### ISSUE TITLE
5. Customer Account Balance

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#5]
Define a class Customer having three variables "name","account_no" & "balance". It must initialise the class object with the name of the customer, auto-increment the account no and set balance to 1000. Define methods deposit() and withdraw() for this class.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Customer

**Comment by segunadeleye** [comment]
How about making `$account_number` a class variable?
I should not be able to withdraw or deposit zero or negative values. You need to put this into consideration as wll.

**Comment by ghost** [comment]
Done

**Comment by segunadeleye** [comment]
- Global variable `$customer`? in  main.rb
- Put in separate lines to enhance readability
  https://github.com/adebayo-dealdey/RubyTrack/blob/master/Customer/lib/customer.rb#L7

**Comment by ghost** [comment]
Done thanks

**Comment by segunadeleye** [comment]
Looks good
