### ISSUE TITLE
6. Vehicle - Subclass

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#6]
Define a class named 'Vehicle' consisting of 'name','price' and methods for initializing and showing contents. The 'price' of Vehicle may change over time. Now create a subclass 'Bike' having 'dealer' and method to show its content. Initialize a Bike class object with certain values and then change its price.

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Vehicle

**Comment by segunadeleye** [comment]
Looks good.
- Remove the `attr` definitions if they are not used.
- Read about that here http://stackoverflow.com/questions/5046831/why-use-rubys-attr-accessor-attr-reader-and-attr-writer

**Comment by ghost** [comment]
Don't mind me, I didn't do proper code cleaning... Most of the code were not written the way it is now, I had to write it first in a way that needs the attr before going through them again, remember I said I was going through the codes again. Thanks for the correction, I'll take note of that.

**Comment by ghost** [comment]
I checked the code, the attr is needed in all the instance cases it was used. Check the main.rb file to see why I need them. Thanks.

**Comment by adebayo-dealdey** [comment]
No, It is not needed.
