### ISSUE TITLE
7. Inverse Case

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#7]
Overwrite the default 'to_s' method such that it inverses the case of each letter.Eg: "hello WORLD".to_s -> "HELLO world"

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Inverse

**Comment by segunadeleye** [comment]
Use monkey patching.

**Comment by ghost** [comment]
Changes made

**Comment by segunadeleye** [comment]
Why this `word = String(gets.chomp)`?

**Comment by ghost** [comment]
I used it to enforce a string data type, it is good sometimes to enforce a type of data for inputs. Do you want me to change it?

**Comment by segunadeleye** [comment]
`String()` is needed. Input from the command line is already a string.
