### ISSUE TITLE
8. Power - Array

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#8]
Define a method power() for an array. It takes an argument 'x' and returns the array with elements raised to power 'x'. Try to make use of array functions.
Eg: [1,2,3,4,5,6].power(3) -> [1, 8, 27, 64, 125, 216]

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Power

**Comment by segunadeleye** [comment]
Check out `Array#map` and `Array#collect`.

**Comment by ghost** [comment]
Should I just check it out or use it in the exercise, guess the exercise does what it is suppose to do, If you want me to change the syntax i will though.

**Comment by segunadeleye** [comment]
Check them out and use either of the two.

**Comment by ghost** [comment]
I just did, you can check it out. Thanks.

**Comment by segunadeleye** [comment]
https://github.com/adebayo-dealdey/RubyTrack/blob/master/Power/lib/array.rb#L3
`self` is not needed.

Closing this now, but make the necessary corrections

**Comment by ghost** [comment]
I just did that, thanks.
