### ISSUE TITLE
9. Array - Hash

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#9]
Create a method for Array that can create a hash having 'key' as length of the element and value as an array of all the elements of that length. Make use of for-in loop for the purpose.Eg: ['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'] should give result as {3=>["abc", "def", 234], 4=>[1234, "abcd", "mnop", "zZzZ"], 1=>["x", 5]}

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Hash

**Comment by segunadeleye** [comment]
You can set default values for the hash keys so there would be no need to check if the key exists or not.

**Comment by ghost** [comment]
I just adjusted that now. Pushed it already

**Comment by segunadeleye** [comment]
Look at passing a block to `Hash.new` to set default value.
Use a more appropriate/descriptive method name. `to_hash` doesn't tell us what's happening in the method

**Comment by ghost** [comment]
I just did, thanks.

**Comment by segunadeleye** [comment]
Looks good.
Always remove commented code if it's not for information.
